language: php
php:
  - "5.6"
before_script:
  - composer selfupdate
  - COMPOSER_ROOT_VERSION=dev-master composer install
notifications:
  email:
    - "team@objective-php.org"
script:
  - tests/phpunit tests/Application
